#!/usr/bin/env Rscript
# Config plumbing for the two pod wrappers beside this file. Two subcommands:
#
#   nli_pods.R conf            emit output/config/runpod_nli_<ACTIVE>.conf and
#                              print shell-eval'able ACTIVE/COUNT/CONF/CSV
#   nli_pods.R hosts <csv>     write the started hosts back into
#                              input/config.yaml's active nli config
#
# It is R rather than bash because the only comment-preserving YAML tool (yq)
# is not installed here, and the write-back below needs to PARSE the result to
# check it before trusting it. jq cannot read YAML and a bash regex cannot tell
# a `host:` inside the active config from one three configs further down.

suppressPackageStartupMessages(library(yaml))

CONFIG <- "input/config.yaml"
OUTDIR <- "output/config"

die <- function(...) stop(sprintf(...), call. = FALSE)

active_nli <- function(cfg) {
  fc <- cfg[["fact_checking"]]
  if (is.null(fc)) die("config.yaml has no fact_checking: block")
  a <- fc[["active"]]
  if (is.null(a)) die("fact_checking: has no active: -- this script needs the library+active shape")
  sel <- fc[["configs"]][[a]]
  if (is.null(sel)) die("fact_checking.active: '%s' is not a defined config", a)
  n <- sel[["nli"]]
  if (is.null(cfg[["nli"]][["configs"]][[n]])) die("nli.configs.%s does not exist", n)
  n
}

# ---------------------------------------------------------------- conf -----
emit_conf <- function() {
  cfg <- read_yaml(CONFIG)
  name <- active_nli(cfg)
  nli <- cfg[["nli"]][["configs"]][[name]]
  defaults <- cfg[["nli"]][["pod_defaults"]] %||% list()
  pods <- nli[["pods"]]
  if (is.null(pods)) die("nli.configs.%s has no pods: block -- nothing to launch", name)
  if (is.null(nli[["image"]])) die("nli.configs.%s has no image:", name)

  count <- pods[["count"]]
  if (is.null(count) || !is.numeric(count) || count < 1) die("nli.configs.%s.pods.count must be a positive number", name)

  # NLI_MAX_LENGTH is DERIVED from max_length, never restated. A pod serving a
  # 512-trained model at 2048 raises nothing and merely scores worse (a8c6ea4);
  # deriving it removes the mismatch instead of detecting it later.
  env <- pods[["extra_env"]] %||% list()
  want <- nli[["max_length"]]
  if (!is.null(want)) {
    if (!is.null(env[["NLI_MAX_LENGTH"]]) &&
          as.integer(env[["NLI_MAX_LENGTH"]]) != as.integer(want)) {
      die("nli.configs.%s: pods.extra_env.NLI_MAX_LENGTH (%s) contradicts max_length (%s). Remove it -- it is derived.",
          name, env[["NLI_MAX_LENGTH"]], want)
    }
    env[["NLI_MAX_LENGTH"]] <- as.integer(want)
  }

  # yaml key -> conf variable. Everything not listed here is passed through as
  # its own upper-cased name, which covers every pod_defaults field.
  special <- c(name_prefix = "POD_NAME_PREFIX")
  merged <- utils::modifyList(defaults, pods[setdiff(names(pods), c("count", "extra_env"))])
  merged[["IMAGE"]] <- nli[["image"]]

  lines <- c(
    "# GENERATED by scripts/runpod/nli_pods.R from input/config.yaml.",
    sprintf("# nli config: %s   (fact_checking.active: %s)", name, cfg$fact_checking$active),
    "# Disposable: regenerated on every start, never edited by hand.",
    ""
  )
  for (k in names(merged)) {
    v <- merged[[k]]
    if (is.null(v)) next
    var <- if (k %in% names(special)) special[[k]] else toupper(k)
    lines <- c(lines, sprintf("%s=%s", var, shQuote(as.character(v))))
  }
  if (length(env)) {
    lines <- c(lines, "EXTRA_ENV=(",
               sprintf("  %s", shQuote(paste0(names(env), "=", unlist(env)))), ")")
  }

  dir.create(OUTDIR, recursive = TRUE, showWarnings = FALSE)
  conf <- file.path(OUTDIR, sprintf("runpod_nli_%s.conf", name))
  csv <- file.path(OUTDIR, sprintf("runpod_nli_%s_hosts.csv", name))
  writeLines(lines, conf)

  cat(sprintf("ACTIVE=%s\nCOUNT=%d\nCONF=%s\nCSV=%s\n", name, as.integer(count), conf, csv))
}

# --------------------------------------------------------------- hosts -----
# A SURGICAL single-line replacement, not a YAML round-trip: 294 of
# config.yaml's lines are comments carrying this project's design rationale,
# and write_yaml() would erase every one of them. Every host: entry is a
# single-line flow list, which is what makes one-line replacement possible.
write_hosts <- function(csv) {
  if (!file.exists(csv)) die("no hosts csv at %s", csv)
  rows <- utils::read.csv(csv, stringsAsFactors = FALSE)
  hosts <- rows$host[nzchar(rows$host)]

  cfg <- read_yaml(CONFIG)
  name <- active_nli(cfg)
  lines <- readLines(CONFIG, warn = FALSE)

  # The active config's block runs from its own key to the next key at the same
  # indent. Find the single host: line inside it.
  start <- grep(sprintf("^    %s:\\s*$", name), lines)
  if (length(start) != 1L) die("could not locate a unique `    %s:` line in %s", name, CONFIG)
  rest <- lines[(start + 1L):length(lines)]
  ends <- grep("^    \\S", rest)
  stop_at <- if (length(ends)) start + ends[[1L]] - 1L else length(lines)
  hit <- grep("^      host:", lines[start:stop_at])
  if (length(hit) != 1L) die("expected exactly one `host:` line in nli.configs.%s, found %d", name, length(hit))
  idx <- start + hit[[1L]] - 1L

  new <- sprintf("      host: [%s]", paste(sprintf('"%s"', hosts), collapse = ", "))
  if (identical(lines[[idx]], new)) { message("[nli_pods] host: already up to date"); return(invisible()) }
  cand <- lines; cand[[idx]] <- new

  tmp <- tempfile(fileext = ".yaml")
  writeLines(cand, tmp)
  parsed <- tryCatch(read_yaml(tmp), error = function(e)
    die("the edited config does not parse (%s) -- %s left untouched", conditionMessage(e), CONFIG))

  # Nothing but that one key may have moved. Blank both out and compare the rest.
  a <- cfg; b <- parsed
  a$nli$configs[[name]]$host <- NULL; b$nli$configs[[name]]$host <- NULL
  if (!identical(a, b)) die("the edit changed more than nli.configs.%s.host -- %s left untouched", name, CONFIG)
  if (sum(cand != lines) != 1L) die("the edit changed %d lines, expected 1 -- %s left untouched", sum(cand != lines), CONFIG)

  writeLines(cand, CONFIG)
  message(sprintf("[nli_pods] nli.configs.%s.host <- %d host(s)", name, length(hosts)))
}

`%||%` <- function(x, y) if (is.null(x)) y else x
args <- commandArgs(trailingOnly = TRUE)
switch(args[[1L]] %||% "",
  conf  = emit_conf(),
  hosts = write_hosts(args[[2L]]),
  die("usage: nli_pods.R conf | nli_pods.R hosts <csv>")
)
